<a href="https://colab.research.google.com/github/Void-Brain70/Machine_Learning/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
LR = LogisticRegression()
LR.fit(x_train,y_train)
LR.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9740740740740741

In [4]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [5]:
RF = RandomForestClassifier(n_estimators=40)
RF.fit(x_train,y_train)
RF.score(x_test,y_test)

0.9648148148148148

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf 

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
kf.split([1,2,3,4,5,6,7,8,9])

<generator object _BaseKFold.split at 0x7f50bc892550>

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [11]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9740740740740741

In [12]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9888888888888889

In [13]:
from sklearn.model_selection import StratifiedKFold
f = StratifiedKFold(n_splits=3)

lr = []
sv = []
rf = []

for train_index,test_index in f.split(digits.data,digits.target):
  x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
  lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test)) 
  sv.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))                               



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [14]:
lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [15]:
sv

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [16]:
rf

[0.9348914858096828, 0.9532554257095158, 0.9265442404006677]

In [17]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target) # cv=n;n=1,2,3,4,....

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [18]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [19]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.90555556, 0.95543175, 0.96657382, 0.92200557])