<a href="https://colab.research.google.com/github/Void-Brain70/Machine_Learning/blob/main/Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
# from word2number import w2n

In [2]:
df = pd.read_csv('/content/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
# y = m1x1 + m2x2 + m3x3 +b
# m1,m2,m3 are coefficient
# x1,x2,x3 are independent variables
# y is dependent variabel
# b is intercept
# m1=112.06244194 ,m2=23388.88007794 , m3= -3231.71790863
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
# b = 221323.00186540396
reg.intercept_

221323.00186540396

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [13]:
112.06244194*3000+23388.88007794*3+(-3231.71790863)*40+221323.00186540396

498408.251574024

In [14]:
reg.predict([[2500,4,5]])

array([578876.03748933])

Exercise

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [16]:
df = pd.read_csv('/content/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
# df.experience = df.experience.apply(w2n.word_to_num)
# df

In [26]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [27]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [29]:
# reg = linear_model.LinearRegression()
# reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

In [ ]:
reg.predict([[2,9,6]])

In [ ]:
reg.predict([[12,10,10]])