<a href="https://colab.research.google.com/github/Void-Brain70/Machine_Learning/blob/main/SaveModel_Joblib_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("/content/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
reg  = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.coef_

array([135.78767123])

In [6]:
reg.intercept_

180616.43835616432

In [9]:
reg.predict([[5000]])

array([859554.79452055])

Save Model To a File Using Python Pickle

In [10]:
import pickle

In [15]:
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

In [16]:
with open('model_pickle','rb') as f:
  mp = pickle.load(f)

In [17]:
mp.coef_

array([135.78767123])

In [18]:
mp.intercept_

180616.43835616432

In [19]:
mp.predict([[5000]])

array([859554.79452055])


Save Trained Model Using joblib

In [29]:
# !pip

In [23]:
from sklearn.externals import joblib

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [24]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.coef_

array([135.78767123])

In [27]:
mj.intercept_

180616.43835616432

In [28]:
mj.predict([[5000]])

array([859554.79452055])